export {
  trackEvent,
  trackCheckout,
  trackSearch,
  trackPlayback,
  trackDownload,
  trackSignup,
  trackLogin,
  trackSubscription,
  trackWatchParty,
  type AnalyticsEvent,
  type BaseEventData,
  type CheckoutEventData,
  type SearchEventData,
  type PlaybackEventData,
  type DownloadEventData,
  type SignupEventData,
  type LoginEventData,
  type SubscriptionEventData,
  type WatchPartyEventData,
} from './analytics';
